In [ ]:
import pandas as pd
import numpy as np


In [ ]:
df=pd.read_csv('/abalone.csv')

FileNotFoundError: ignored

In [ ]:
df

NameError: ignored

In [ ]:
y=df.iloc[:,0]
x=df.iloc[:,1:]

NameError: ignored

In [ ]:
x.isnull().sum()

LongestShell     0
Diameter         0
Height           0
WholeWeight      0
ShuckedWeight    0
VisceraWeight    0
ShellWeight      0
Rings            0
dtype: int64

In [ ]:
y.unique()

array(['M', 'F', 'I'], dtype=object)

###pca
pca is unsuppervised technique so we only handle x.

#scalling

In [ ]:
import sklearn
sklearn.preprocessing.StandardScaler 

In [ ]:
#mean centric scaliing
mean_data=np.mean(x.T,axis=1)

scaled_data=x-mean_data
scaled_data

LongestShell  Diameter    Height  WholeWeight  ShuckedWeight  \
0        -0.068992 -0.042881 -0.044516    -0.314742      -0.134867   
1        -0.173992 -0.142881 -0.049516    -0.603242      -0.259867   
2         0.006008  0.012119 -0.004516    -0.151742      -0.102867   
3        -0.083992 -0.042881 -0.014516    -0.312742      -0.143867   
4        -0.193992 -0.152881 -0.059516    -0.623742      -0.269867   
...            ...       ...       ...          ...            ...   
4172      0.041008  0.042119  0.025484     0.058258       0.010633   
4173      0.066008  0.032119 -0.004516     0.137258       0.079633   
4174      0.076008  0.067119  0.065484     0.347258       0.166133   
4175      0.101008  0.077119  0.010484     0.265758       0.171633   
4176      0.186008  0.147119  0.055484     1.119758       0.586133   

      VisceraWeight  ShellWeight     Rings  
0         -0.079594    -0.088831  5.066316  
1         -0.132094    -0.168831 -2.933684  
2         -0.039094    -0.028831 -0.933684  
3         -0.066594    -0.083831  0.066316  
4         -0.141094    -0.183831 -2.933684  
...             ...          ...       ...  
4172       0.058406     0.010169  1.066316  
4173       0.033906     0.021669  0.066316  
4174       0.106906     0.069169 -0.933684  
4175       0.080406     0.057169  0.066316  
4176       0.195906     0.256169  2.066316  

[4177 rows x 8 columns]

In [ ]:
from sklearn

##creating covariance matrix

In [ ]:
cov_mat=np.cov(scaled_data.T)
cov_mat

array([[1.44223076e-02, 1.17608250e-02, 4.15691189e-03, 5.44907081e-02,
        2.39349454e-02, 1.18872298e-02, 1.50071720e-02, 2.15561736e-01],
       [1.17608250e-02, 9.84855103e-03, 3.46054721e-03, 4.50381820e-02,
        1.96742019e-02, 9.78729548e-03, 1.25066369e-02, 1.83871673e-01],
       [4.15691189e-03, 3.46054721e-03, 1.74950266e-03, 1.68034708e-02,
        7.19488681e-03, 3.66016741e-03, 4.75889986e-03, 7.51786501e-02],
       [5.44907081e-02, 4.50381820e-02, 1.68034708e-02, 2.40481389e-01,
        1.05518032e-01, 5.19461632e-02, 6.52158684e-02, 8.54408544e-01],
       [2.39349454e-02, 1.96742019e-02, 7.19488681e-03, 1.05518032e-01,
        4.92675507e-02, 2.26749006e-02, 2.72709563e-02, 3.01203734e-01],
       [1.18872298e-02, 9.78729548e-03, 3.66016741e-03, 5.19461632e-02,
        2.26749006e-02, 1.20152839e-02, 1.38495613e-02, 1.78057215e-01],
       [1.50071720e-02, 1.25066369e-02, 4.75889986e-03, 6.52158684e-02,
        2.72709563e-02, 1.38495613e-02, 1.93773832e-02, 2.

##finding eigen vector

In [ ]:
eigen_val , eigen_vec = np.linalg.svd(cov_mat)
print(eigen_val)
print(eigen_vec)

[1.04954314e+01 2.39268823e-01 3.02087647e-03 2.60218996e-03
 1.05068657e-03 1.47688518e-04 4.88782005e-04 4.17493194e-04]
[[-2.10513202e-02  1.83052752e-01 -7.42040211e-01  9.06887398e-02
   3.07007218e-02 -6.18893826e-01  1.52311416e-01 -5.43508715e-03]
 [-1.79401219e-02  1.48804192e-01 -5.96175335e-01  4.20854302e-02
  -2.33409653e-02  7.83141972e-01  7.49734266e-02 -2.93613363e-02]
 [-7.31629638e-03  5.24595599e-02 -1.40358287e-01 -3.71173260e-02
  -1.45782231e-03 -4.21715859e-02 -9.10437257e-01 -3.81365645e-01]
 [-8.36804920e-02  8.34461310e-01  2.28847916e-01 -2.20616051e-01
   1.25570884e-01 -2.50039224e-03  1.82698066e-01 -3.82722100e-01]
 [-2.97346596e-02  3.99951598e-01  1.36354791e-01  7.54544047e-01
  -3.31709499e-01  5.43703582e-03 -1.68819392e-01  3.35655300e-01]
 [-1.74599170e-02  1.83252786e-01 -7.74498237e-03 -7.33235758e-02
   7.56051666e-01  2.91035964e-02 -2.30202123e-01  5.78984522e-01]
 [-2.74311519e-02  2.05272453e-01 -5.65032111e-02 -6.04242412e-01
  -5.48722324

##projecting the data to new axis

In [ ]:
project_data = eigen_vec.T.dot(scaled_data.T)

In [ ]:
project_data

array([[-5.00480331e+00,  2.99106199e+00,  9.46034953e-01, ...,
         8.88069923e-01, -9.98918993e-02, -2.18474351e+00],
       [-8.66926554e-01, -4.34571636e-01, -8.67386708e-02, ...,
         5.08786202e-01,  3.40899859e-01,  1.11378693e+00],
       [ 2.78764323e-02,  4.11496350e-02, -6.33340395e-02, ...,
        -1.36851112e-02, -4.16435072e-02,  9.87562350e-02],
       ...,
       [ 9.97555349e-03,  3.62569288e-04,  5.84371714e-03, ...,
         4.01045146e-03, -1.77778014e-03, -4.88393630e-03],
       [ 2.71492360e-02, -1.29678387e-03,  8.97410940e-03, ...,
        -4.40523291e-02,  3.25214931e-03,  7.79768784e-03],
       [ 9.60914417e-03,  1.09468006e-03, -1.37480744e-02, ...,
        -8.69095613e-03,  2.48454648e-02, -1.15286400e-02]])

##comparing wiht the sklearn pca function

In [ ]:
from sklearn.decomposition import PCA

pca=PCA()
pca.fit(scaled_data)
p=pca.fit_transform(scaled_data)


In [ ]:
p

array([[ 5.00480331e+00, -8.66926554e-01,  2.78764323e-02, ...,
        -2.71492360e-02, -9.60914417e-03,  9.97555349e-03],
       [-2.99106199e+00, -4.34571636e-01,  4.11496350e-02, ...,
         1.29678387e-03, -1.09468006e-03,  3.62569288e-04],
       [-9.46034953e-01, -8.67386708e-02, -6.33340395e-02, ...,
        -8.97410940e-03,  1.37480744e-02,  5.84371714e-03],
       ...,
       [-8.88069923e-01,  5.08786202e-01, -1.36851112e-02, ...,
         4.40523291e-02,  8.69095613e-03,  4.01045146e-03],
       [ 9.98918993e-02,  3.40899859e-01, -4.16435072e-02, ...,
        -3.25214931e-03, -2.48454648e-02, -1.77778014e-03],
       [ 2.18474351e+00,  1.11378693e+00,  9.87562350e-02, ...,
        -7.79768784e-03,  1.15286400e-02, -4.88393630e-03]])

In [ ]:
pca.explained_variance_ratio_

array([9.77007382e-01, 2.22732538e-02, 2.81209843e-04, 2.42234808e-04,
       9.78071788e-05, 4.55001428e-05, 3.88639512e-05, 1.37481507e-05])

In [ ]:
pca.inverse_transform(p)

array([[-6.89920996e-02, -4.28812545e-02, -4.45163993e-02, ...,
        -7.95936079e-02, -8.88308595e-02,  5.06631554e+00],
       [-1.73992100e-01, -1.42881254e-01, -4.95163993e-02, ...,
        -1.32093608e-01, -1.68830859e-01, -2.93368446e+00],
       [ 6.00790041e-03,  1.21187455e-02, -4.51639933e-03, ...,
        -3.90936079e-02, -2.88308595e-02, -9.33684463e-01],
       ...,
       [ 7.60079004e-02,  6.71187455e-02,  6.54836007e-02, ...,
         1.06906392e-01,  6.91691405e-02, -9.33684463e-01],
       [ 1.01007900e-01,  7.71187455e-02,  1.04836007e-02, ...,
         8.04063921e-02,  5.71691405e-02,  6.63155375e-02],
       [ 1.86007900e-01,  1.47118746e-01,  5.54836007e-02, ...,
         1.95906392e-01,  2.56169141e-01,  2.06631554e+00]])

In [ ]:
#calculating loading

loading=pd.DataFrame(pca.components_.T,columns=['pc1','pc2','pc3','pc4','pc5','pc6','pc7','pc8'])
loading

pc1       pc2       pc3       pc4       pc5       pc6       pc7  \
0  0.021051  0.183053 -0.742040 -0.090689 -0.030701 -0.152311  0.005435   
1  0.017940  0.148804 -0.596175 -0.042085  0.023341 -0.074973  0.029361   
2  0.007316  0.052460 -0.140358  0.037117  0.001458  0.910437  0.381366   
3  0.083680  0.834461  0.228848  0.220616 -0.125571 -0.182698  0.382722   
4  0.029735  0.399952  0.136355 -0.754544  0.331709  0.168819 -0.335655   
5  0.017460  0.183253 -0.007745  0.073324 -0.756052  0.230202 -0.578985   
6  0.027431  0.205272 -0.056503  0.604242  0.548722  0.165567 -0.509218   
7  0.995107 -0.097937  0.005853 -0.011544 -0.000995 -0.000404 -0.001407   

        pc8  
0 -0.618894  
1  0.783142  
2 -0.042172  
3 -0.002500  
4  0.005437  
5  0.029104  
6 -0.031587  
7 -0.000308

#raw code from more basic

In [ ]:
import pandas as pd
from pandas import DataFrame
import numpy as np

In [ ]:
di={'x':[4,8,13,7],'y':[11,4,5,14]}
df=pd.DataFrame(di)

In [ ]:
list(df['x'])
list(df.columns)

['x', 'y']

In [ ]:
def mean_var(l):
  sum=0
  for i in list(l):
    sum+=i
  mean=sum/len(l)
  return mean

In [ ]:
mean_var(df['y'])

8.5

manual code for covariance (not requierd)

In [ ]:
# def cov(df:pd.DataFrame):
#   col_l=list(df.columns)
#   n=len(col_l)
#   #covariance matrix will be my s
#   s=np.empty([n,n])
#   for i in range(n):
#     for j in range(n):
#       s[i][j]=


#step 1 eigen value